# Prompt template generated by RISC-V assembly code

# RISC-V register and instruction description (concise version)
RISCV_INSTRUCTION_GUIDE = """
# RISC-V 64-bit register (must use the following names)

General-purpose registers:
- zero (x0): constant zero
- ra (x1): return address
- sp (x2): stack pointer
- gp (x3): global pointer
- tp (x4): thread pointer
- t0-t6 (x5-x7, x28-x31): temporary registers. Note that only t0-t6 exist; t7/t8/t9 are invalid.
- s0-s11 (x8-x9, x18-x27): saved registers
- a0-a7 (x10-x17): argument and return-value registers

Floating-point registers, if needed:
- f0-f31, or the ABI names ft0-ft11, fs0-fs11, fa0-fa7

# Common Mistakes (Avoid)
- t7, t8, and t9 do not exist.
- ARM-style names such as r0, r1, and r2 are invalid.
- x86-style names such as eax and ebx are invalid.
"""

# Basic assembly template
asm_template = """
'''assembly
.section .text
.global _start

_start:
    # Write test code here.
    # Recommended: use loops, jumps, and branches to increase test coverage.
    # Recommended: generate 50-200 instructions to trigger hardware logic.
    # Important: only use these registers: t0-t6, s0-s11, a0-a7, zero, ra, sp, gp, tp.
    
    # Your test instructions...
    
    # === Program exit sequence. Keep this block unchanged. ===
    li      gp, 1
    li      a7, 93
    li      a0, 0
    ecall
    unimp
'''
"""

# Test example with loop
asm_template_with_loop = """
.section .text
.global _start

_start:
    # Initialize test data
    li t0, 0x12345678
    li t1, 0x87654321
    li t2, 100          # loop count
    
loop_start:
    # Perform various operations to trigger different hardware paths
    add t3, t0, t1
    sub t4, t0, t1
    xor t5, t0, t1
    and t6, t0, t1
    or s0, t0, t1
    sll s1, t0, t1
    srl s2, t0, t1
    sra s3, t0, t1
    
    # update value
    addi t0, t0, 1
    xori t1, t1, 0xFF
    
    # loop control
    addi t2, t2, -1
    bnez t2, loop_start
    
    # More tests...
    mul a0, t3, t4
    div a1, t5, t6
    rem a2, s0, s1
    
    # Program exits
    li      gp, 1
    li      a7, 93
    li      a0, 0
    ecall
    unimp
"""

# Boundary testing example
asm_template_boundary = """
.section .text
.global _start

_start:
    # Boundary value testing
    li t0, 0x7FFFFFFFFFFFFFFF   # largest positive number
    li t1, 0x8000000000000000   # smallest negative number
    li t2, 0xFFFFFFFFFFFFFFFF   # -1
    li t3, 0                     # zero
    li t4, 1                     # smallest positive number
    
    # Boundary operations
    add t5, t0, t4      # Overflow testing
    sub t6, t1, t4      # underflow test
    mul s0, t0, t2      # Multiplication of large numbers
    div s1, t1, t2      # special division
    
    # shift boundary
    slli s2, t4, 63     # Move left to the highest position
    srli s3, t1, 63     # Shift right to sign bit
    srai s4, t1, 63     # arithmetic right shift
    
    # Program exits
    li      gp, 1
    li      a7, 93
    li      a0, 0
    ecall
    unimp
"""

# CSR operations test template
asm_template_csr = """
.section .text
.global _start

_start:
    # CSR register test
    # Read various CSR registers
    csrr t0, 0x300       # mstatus
    csrr t1, 0x305       # mtvec
    csrr t2, 0x341       # mepc
    csrr t3, 0x342       # mcause
    
    # Write to CSR register
    li t4, 0x1800
    csrw 0x300, t4       # Set mstatus
    
    # read-modify-write
    csrrs t5, 0x300, t4  # set specific bit
    csrrc t6, 0x300, t4  # clear specific bit
    
    # Program exits
    li      gp, 1
    li      a7, 93
    li      a0, 0
    ecall
    unimp
"""

# Memory access test template
asm_template_memory = """
.section .text
.global _start

_start:
    # Memory access test
    la t0, test_data     # Load data address
    
    # Loading of various widths
    lb t1, 0(t0)         # Byte loading
    lh t2, 0(t0)         # half word load
    lw t3, 0(t0)         # word loading
    ld t4, 0(t0)         # double word load
    
    # unsigned load
    lbu t5, 0(t0)
    lhu t6, 0(t0)
    lwu s0, 0(t0)
    
    # storage test
    sb t1, 8(t0)
    sh t2, 16(t0)
    sw t3, 24(t0)
    sd t4, 32(t0)
    
    # Program exits
    li      gp, 1
    li      a7, 93
    li      a0, 0
    ecall
    unimp

.section .data
test_data:
    .dword 0x123456789ABCDEF0
    .dword 0xFEDCBA9876543210
    .space 64
"""

# Branch and jump test template
asm_template_branch = """
.section .text
.global _start

_start:
    # branch testing
    li t0, 10
    li t1, 10
    li t2, 5
    li t3, 20
    
    # Equal/unequal branch
    beq t0, t1, equal_label
    j skip1
equal_label:
    addi t4, zero, 1
skip1:
    
    bne t0, t2, not_equal_label
    j skip2
not_equal_label:
    addi t4, zero, 2
skip2:
    
    # compare branches
    blt t2, t0, less_than_label
less_than_label:
    
    bge t3, t0, greater_equal_label
greater_equal_label:
    
    # unsigned comparison
    li t5, 0xFFFFFFFFFFFFFFFF
    bltu t0, t5, unsigned_less
unsigned_less:
    
    # Program exits
    li      gp, 1
    li      a7, 93
    li      a0, 0
    ecall
    unimp
"""

# Multiplication and division test template
asm_template_muldiv = """
.section .text
.global _start

_start:
    # Multiplication and division test
    li t0, 12345
    li t1, 67890
    li t2, -12345
    li t3, 0
    
    # multiplication
    mul a0, t0, t1       # Signed multiplication (lower 64 bits)
    mulh a1, t0, t1      # Signed multiplication (high 64 bits)
    mulhu a2, t0, t1     # Unsigned multiplication (high 64 bits)
    mulhsu a3, t2, t1    # Signed*Unsigned
    
    # division
    li t4, 1000
    li t5, 7
    div a4, t4, t5       # signed division
    divu a5, t4, t5      # unsigned division
    rem a6, t4, t5       # signed remainder
    remu a7, t4, t5      # unsigned remainder
    
    # Boundary case: divide by zero (may trigger exception)
    # div s0, t0, t3 # divide by zero - use with caution
    
    # Program exits
    li      gp, 1
    li      a7, 93
    li      a0, 0
    ecall
    unimp
"""

# Illegal register map for automatic repair.
ILLEGAL_REGISTER_MAP = {
    't7': 's0', 't8': 's1', 't9': 's2', 't10': 's3', 't11': 's4', 't12': 's5',
    'r0': 'zero', 'r1': 'ra', 'r2': 'sp', 'r3': 'gp', 'r4': 'tp',
    'r5': 't0', 'r6': 't1', 'r7': 't2', 'r8': 's0', 'r9': 's1',
    'r10': 'a0', 'r11': 'a1', 'r12': 'a2', 'r13': 'a3', 'r14': 'a4', 'r15': 'a5',
    # x86-style register names.
    'eax': 'a0', 'ebx': 'a1', 'ecx': 'a2', 'edx': 'a3',
    'rax': 'a0', 'rbx': 'a1', 'rcx': 'a2', 'rdx': 'a3',
}

# Legal RISC-V registers.
LEGAL_REGISTERS = {
    'zero', 'ra', 'sp', 'gp', 'tp',
    't0', 't1', 't2', 't3', 't4', 't5', 't6',
    's0', 's1', 's2', 's3', 's4', 's5', 's6', 's7', 's8', 's9', 's10', 's11',
    'a0', 'a1', 'a2', 'a3', 'a4', 'a5', 'a6', 'a7',
    'fp', # alias for s0
    # x-style register names are also legal.
    'x0', 'x1', 'x2', 'x3', 'x4', 'x5', 'x6', 'x7',
    'x8', 'x9', 'x10', 'x11', 'x12', 'x13', 'x14', 'x15',
    'x16', 'x17', 'x18', 'x19', 'x20', 'x21', 'x22', 'x23',
    'x24', 'x25', 'x26', 'x27', 'x28', 'x29', 'x30', 'x31',
    # Floating-point registers.
    'f0', 'f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7',
    'f8', 'f9', 'f10', 'f11', 'f12', 'f13', 'f14', 'f15',
    'f16', 'f17', 'f18', 'f19', 'f20', 'f21', 'f22', 'f23',
    'f24', 'f25', 'f26', 'f27', 'f28', 'f29', 'f30', 'f31',
    'ft0', 'ft1', 'ft2', 'ft3', 'ft4', 'ft5', 'ft6', 'ft7',
    'ft8', 'ft9', 'ft10', 'ft11',
    'fs0', 'fs1', 'fs2', 'fs3', 'fs4', 'fs5', 'fs6', 'fs7',
    'fs8', 'fs9', 'fs10', 'fs11',
    'fa0', 'fa1', 'fa2', 'fa3', 'fa4', 'fa5', 'fa6', 'fa7',
}
